"""empty message

Revision ID: 01967ffa4455
Revises: 32aedb572100
Create Date: 2024-03-18 15:52:35.800032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01967ffa4455'
down_revision = '32aedb572100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
