"""empty message

Revision ID: 2798314ea899
Revises: c4e307a681c6
Create Date: 2024-01-27 00:41:38.955750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2798314ea899"
down_revision = "7510999f7fe5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review", schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('region_id', sa.Integer(), nullable=False))

        batch_op.create_foreign_key(None, "region", ["region_id"], ["id"])
        batch_op.create_foreign_key(None, "user", ["user_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")

    # ### end Alembic commands ###
