"""empty message

Revision ID: 5f93d264398b
Revises: bdc6754af1fc
Create Date: 2024-01-02 21:05:08.178311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f93d264398b'
down_revision = 'bdc6754af1fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('upvotes',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('downvotes',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('downvotes',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('upvotes',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
