"""empty message

Revision ID: 7b653f89a4fd
Revises: 
Create Date: 2024-01-28 18:45:59.554739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7b653f89a4fd"
down_revision = "d84fc4262100"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.String(length=100), nullable=False),
        sa.Column("content", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("upvotes", sa.Integer(), nullable=True),
        sa.Column("downvotes", sa.Integer(), nullable=True),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "region",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("city"),
        sa.UniqueConstraint("public_id"),
    )

    # op.drop_table("testdb")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table(
    #     "testdb",
    #     sa.Column(
    #         "id",
    #         sa.BIGINT(),
    #         sa.Identity(
    #             always=False,
    #             start=1,
    #             increment=1,
    #             minvalue=1,
    #             maxvalue=9223372036854775807,
    #             cycle=False,
    #             cache=1,
    #         ),
    #         autoincrement=True,
    #         nullable=False,
    #     ),
    #     sa.Column(
    #         "created_at",
    #         postgresql.TIMESTAMP(timezone=True),
    #         server_default=sa.text("now()"),
    #         autoincrement=False,
    #         nullable=False,
    #     ),
    #     sa.PrimaryKeyConstraint("id", name="testdb_pkey"),
    #     comment="for testing",
    # )
    op.drop_table("region")
    op.drop_table("comment")
    # ### end Alembic commands ###
