"""empty message

Revision ID: a56472c28b6b
Revises: 0c24258584cc
Create Date: 2024-01-27 19:46:40.569812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a56472c28b6b'
down_revision = '0c24258584cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint('review_ibfk_4', type_='foreignkey')
        batch_op.drop_column('review_tag_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_tag_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('review_ibfk_4', 'review_tag', ['review_tag_id'], ['id'])

    # ### end Alembic commands ###