"""update comment model

Revision ID: cefac2fe8bf5
Revises: 74b1de9dcaf4
Create Date: 2023-12-28 11:50:35.513119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cefac2fe8bf5'
down_revision = '74b1de9dcaf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'review_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               nullable=False)
    op.create_unique_constraint(None, 'comment', ['review_id'])
    op.drop_constraint('comment_ibfk_1', 'comment', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('comment_ibfk_1', 'comment', 'review', ['review_id'], ['id'])
    op.drop_constraint(None, 'comment', type_='unique')
    op.alter_column('comment', 'review_id',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
