"""empty message

Revision ID: d89cc31588df
Revises: a56472c28b6b
Create Date: 2024-02-08 04:24:10.360688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89cc31588df'
down_revision = '2798314ea899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'review', ['review_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('review_id')

    # ### end Alembic commands ###
