"""empty message

Revision ID: e455805be8e1
Revises: ecc1ef57b909
Create Date: 2024-01-18 05:01:01.382674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e455805be8e1'
down_revision = 'ecc1ef57b909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index('review_id')
        batch_op.drop_column('review_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_id', mysql.VARCHAR(length=100), nullable=False))
        batch_op.create_index('review_id', ['review_id'], unique=True)

    # ### end Alembic commands ###
